In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
iv = pd.read_csv(r'D:\home loan credit risk\artifact\binning\prebin\iv_df.csv')
x_train = pd.read_csv(r'D:\home loan credit risk\artifact\binning\prebin\X_train_selected_woe.csv')

In [4]:
y_train = pd.read_csv(r'D:\home loan credit risk\artifact\data\data_splits\y_train.csv')

In [5]:
x_train.shape

(246008, 123)

In [6]:
iv[iv['feature'].isin(x_train.columns.tolist())].sort_values(by='IV',ascending=False).head(50)

                                feature        IV
0                   EXT_SOURCE_WEIGHTED  0.626102
4                          EXT_SOURCE_3  0.336897
6                   EXT_SOURCE_X_INCOME  0.278724
7             CREDIT_EXT_SOURCE_PRODUCT  0.183983
8                          EXT_SOURCE_1  0.156080
10                 ANNUITY_CREDIT_RATIO  0.145948
11                   B_DAYS_CREDIT_MEAN  0.121608
12                       YEARS_EMPLOYED  0.114435
13               B_DEBT_TO_CREDIT_RATIO  0.103549
15                      AMT_GOODS_PRICE  0.102669
16                B_ACTIVE_CREDIT_RATIO  0.092495
18                    IP_WORST_DPD_720D  0.091186
19                B_CLOSED_CREDIT_RATIO  0.089606
20                            YEARS_AGE  0.088899
21               CB_MAX_MONTHLY_UTIL_6M  0.087516
22                    B_DAYS_CREDIT_MAX  0.086520
35              PA_RATIO_APPROVED_LOANS  0.078572
40             PA_AVG_RISK_WEIGHT_1080D  0.078007
41             PA_MAX_RISK_WEIGHT_1080D  0.077764
43                   GOODS_CREDIT_RATIO  0.076527
502                    OCCUPATION_GROUP  0.074611
45      BUREAU_DAYS_CREDIT_ENDDATE_MEAN  0.072750
46         IP_RATIO_LATE_PAYMENTS_2160D  0.072576
51        IP_RATIO_EARLY_PAYMENTS_1080D  0.071447
53              PA_MAX_RISK_WEIGHT_720D  0.070734
56                    IP_WORST_DPD_270D  0.069577
57        PA_LOANS_REFUSED_RECENT_1080D  0.069412
58         IP_RATIO_AMT_PAID_OWED_1080D  0.069385
60             B_NUM_ACTIVE_CREDIT_720D  0.068444
64          IP_RATIO_LATE_PAYMENTS_360D  0.063392
74          IP_RATIO_AMT_PAID_OWED_360D  0.058506
503                           ORG_GROUP  0.057884
87         PA_LOANS_REFUSED_RECENT_180D  0.056822
89          PA_LOANS_REFUSED_RECENT_90D  0.056267
504                    NAME_INCOME_TYPE  0.055916
98                           AMT_CREDIT  0.055306
100      BUREAU_DAYS_CREDIT_ENDDATE_MAX  0.054836
102                    IP_WORST_DPD_90D  0.054304
103            B_NUM_ACTIVE_CREDIT_270D  0.054050
104     CB_MAX_RATIO_PAYMENT_BALANCE_3M  0.053877
113         REGION_RATING_CLIENT_W_CITY  0.051572
114      CB_TREND_CREDIT_DRAWING_3M_12M  0.051250
117           B_AMT_CREDIT_SUM_DEBT_SUM  0.050578
119  IP_NUM_UNDERPAID_INSTALLMENTS_720D  0.050435
121     IP_MEAN_INSTALMENT_PAYMENT_DIFF  0.049689
505                 NAME_EDUCATION_TYPE  0.048890
126           PA_RATIO_HC_REFUSED_LOANS  0.048114
127        IP_RATIO_EARLY_PAYMENTS_180D  0.047990
133       CB_AVG_ATM_WITHDRAWAL_FREQ_6M  0.046971
135      CB_WT_CREDIT_UTIL_TREND_3M_12M  0.046865

#### new df

In [9]:
import pandas as pd

df = pd.read_csv(r'D:\home loan credit risk\artifact\data\interim\main_df_transformed.csv',usecols=['SK_ID_CURR','CB_WT_CREDIT_UTIL_TREND_3M_12M','PA_RATIO_CREDIT_APPLICATION_Cash','GOODS_CREDIT_RATIO'])

In [3]:
for col in df.select_dtypes(include=['float64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='float')

In [4]:
df.shape

(100, 557)

#### weights for EXT SOURCE WEIGHTS

In [10]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
ext_features = ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']

imputer = SimpleImputer(strategy='median')
X = imputer.fit_transform(df[ext_features])
y = df['TARGET']
lr = LogisticRegression(max_iter=1000,class_weight='balanced',random_state=23)
lr.fit(X, y)
from sklearn.metrics import classification_report

pred = lr.predict(X)

print(classification_report(y,pred))

# Get coefficients
coefs = lr.coef_[0]
print("EXT_SOURCE Coefficients:", coefs)

              precision    recall  f1-score   support

           0       0.96      0.68      0.79    282686
           1       0.15      0.64      0.24     24825

    accuracy                           0.67    307511
   macro avg       0.55      0.66      0.52    307511
weighted avg       0.89      0.67      0.75    307511

EXT_SOURCE Coefficients: [-1.94047513 -2.4850742  -2.72813311]

In [11]:
len(df.columns)

557

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 557 entries, SK_ID_CURR to CB_WORST_DPD_DEF_96M
dtypes: float32(437), float64(56), int64(44), object(20)
memory usage: 794.2+ MB

In [15]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,YEARS_AGE,YEARS_EMPLOYED,YEARS_REGISTRATION,YEARS_ID_PUBLISH,CREDIT_INCOME_RATIO,ANNUITY_INCOME_RATIO,GOODS_CREDIT_RATIO,ANNUITY_CREDIT_RATIO,ORG_GROUP,DOCUMENT_PROVIDED_FLAG,OCCUPATION_GROUP,FLAG_WORK_PHONE_ENCODED,FLAG_EMP_PHONE_ENCODED,FLAG_PHONE_ENCODED,FLAG_EMAIL_ENCODED,SOCIAL_ANY_DEFAULT,EXT_SOURCE_WEIGHTED,EXT_SOURCE_X_INCOME,EXT_SOURCE_X_AGE,CREDIT_EXT_SOURCE_PRODUCT,EXT_SOURCE_MIN,EXT_SOURCE_MAX,EXT_SOURCE_RANGE,EXT_SOURCE_MISSING_CNT,CREDIT_GOODS_DIFF_AMT,CHILDREN_RATIO,CREDIT_PER_YEAR_AGE,INCOME_TO_AGE_RATIO,EMPLOYMENT_TO_AGE_RATIO,EMPLOYMENT_GAP,REGISTRATION_TO_AGE_RATIO,ID_TO_AGE_RATIO,INCOME_PER_PERSON,ADD_1_CNT_CHILDERN,INCOME_PER_CHILD,ANNUITY_PER_CHILD,CREDIT_PER_PERSON,PHONE_TO_AGE_RATIO,REGION_RATING_DIFF,ANNUITY_TO_AGE_RATIO,TOTAL_BUREAU_REQUESTS,LIVINGAREA_RATIO,NONLIVING_RATIO,FLOOR_RATIO,FINANCIAL_STRESS_SCORE,BURDEN_RISK_INTERACTION,SOCIAL_OBS_DEF_RATIO_30,SOCIAL_OBS_DEF_RATIO_60,PHONE_FLAG_COUNT,INCOME_BY_ORG_TYPE,INCOME_DIFF_FROM_ORG_MEDIAN,BB_WORST_DPD_3M,BB_WORST_DPD_6M,BB_WORST_DPD_9M,BB_WORST_DPD_12M,BB_WORST_DPD_24M,BB_WORST_DPD_36M,BB_WORST_DPD_72M,BB_WORST_DPD_96M,BB_SEVERE_DPD_12M,BB_SEVERE_DPD_24M,BB_SEVERE_DPD_36M,BB_SEVERE_DPD_72M,BB_RECENT_MONTH_OF_DPD,BB_WORST_DPD_ACTIVE_LOANS,MONTHS_BALANCE_MAX,MONTHS_BALANCE_MEAN,MONTHS_BALANCE_SUM,B_NUM_CREDIT_CURRENCIES,B_NUM_ACTIVE_CREDIT_90D,B_NUM_ACTIVE_CREDIT_180D,B_NUM_ACTIVE_CREDIT_270D,B_NUM_ACTIVE_CREDIT_360D,B_NUM_ACTIVE_CREDIT_720D,B_NUM_ACTIVE_CREDIT_1080D,B_DAYS_SINCE_LAST_BAD_LOAN,B_HAS_CREDIT_DAYS_OVERDUE,B_AVG_REPAYMENT_DAYS_DIFF,B_MIN_REPAYMENT_DAYS_DIFF,B_MAX_REPAYMENT_DAYS_DIFF,B_FLAG_HAS_AMT_OVERDUE,B_CREDIT_DAY_OVERDUE_SUM,B_CREDIT_DAY_OVERDUE_MIN,B_CREDIT_DAY_OVERDUE_MAX,B_MAX_CREDIT_PROLONG,B_ACTIVE_DEBT_SUM,B_ACTIVE_CREDIT_SUM,B_RATIO_DEBT_TO_LOAN,B_AMT_CREDIT_SUM_DEBT_MEAN,B_AMT_CREDIT_SUM_DEBT_SUM,B_AMT_CREDIT_SUM_DEBT_MIN,B_AMT_CREDIT_SUM_DEBT_MAX,B_TOTAL_UTIL_RATIO_DEBT_CREDIT,B_TOTAL_ANNUITY_TO_DEBT,B_OVERDUE_TO_CREDIT_RATIO,B_HAS_CREDIT_LOAN,B_DEBT_TO_CREDIT_RATIO,B_DAYS_CREDIT_MEAN,B_DAYS_CREDIT_MAX,B_DAYS_CREDIT_MIN,BUREAU_DAYS_CREDIT_ENDDATE_MEAN,BUREAU_DAYS_CREDIT_ENDDATE_MIN,BUREAU_DAYS_CREDIT_ENDDATE_MAX,B_ACTIVE_CREDIT_COUNT,B_CLOSED_CREDIT_COUNT,B_ACTIVE_CREDIT_RATIO,B_CLOSED_CREDIT_RATIO,B_DEBT_OVERDUE_CNT,BUREAU_OVERDUE_RATE,B_CREDIT_COUNT,B_CREDIT_DURATION_MAX,B_CREDIT_DURATION_MIN,B_CREDIT_DURATION_MEAN,B_AMT_ANNUITY_MAX,B_AMT_ANNUITY_MIN,B_AMT_ANNUITY_MEAN,B_BAD_LOAN_RATE,IP_NUM_OF_RESHEDULES_360D,IP_NUM_OF_RESHEDULES_720D,IP_NUM_OF_RESHEDULES_1080D,IP_NUM_OF_RESHEDULES_1440D,IP_NUM_OF_RESHEDULES_1800D,IP_NUM_OF_RESHEDULES_2160D,IP_AVG_RATIO_PAYMENT_INSTALMENT,IP_MIN_RATIO_PAYMENT_INSTALMENT,IP_MAX_RATIO_PAYMENT_INSTALMENT,IP_RATIO_EARLY_PAYMENTS_90D,IP_RATIO_EARLY_PAYMENTS_180D,IP_RATIO_EARLY_PAYMENTS_270D,IP_RATIO_EARLY_PAYMENTS_360D,IP_RATIO_EARLY_PAYMENTS_720D,IP_RATIO_EARLY_PAYMENTS_1080D,IP_RATIO_EARLY_PAYMENTS_2160D,IP_RATIO_EARLY_PAYMENTS_2880D,IP_RECENT_EARLY_PAYMENT_FLAG_3M,IP_WORST_DPD_90D,IP_WORST_DPD_180D,IP_WORST_DPD_270D,IP_WORST_DPD_360D,IP_WORST_DPD_720D,IP_WORST_DPD_1080D,IP_WORST_DPD_2160D,IP_WORST_DPD_2880D,IP_DPD_TREND,IP_NUM_UNDERPAID_INSTALLMENTS_180D,IP_NUM_UNDERPAID_INSTALLMENTS_360D,IP_NUM_UNDERPAID_INSTALLMENTS_720D,IP_NUM_UNDERPAID_INSTALLMENTS_1080D,IP_NUM_UNDERPAID_INSTALLMENTS_2160D,IP_NUM_UNDERPAID_INSTALLMENTS_2880D,IP_MEAN_INSTALMENT_PAYMENT_DIFF,IP_MIN_INSTALMENT_PAYMENT_DIFF,IP_MAX_INSTALMENT_PAYMENT_DIFF,IP_SUM_INSTALMENT_PAYMENT_DIFF,IP_RATIO_LATE_PAYMENTS_90D,IP_RATIO_LATE_PAYMENTS_180D,IP_RATIO_LATE_PAYMENTS_360D,IP_RATIO_LATE_PAYMENTS_720D,IP_RATIO_LATE_PAYMENTS_1080D,IP_RATIO_LATE_PAYMENTS_2160D,IP_RATIO_MISSED_PAYMENTS_90D,IP_RATIO_MISSED_PAYMENTS_180D,IP_RATIO_MISSED_PAYMENTS_360D,IP_RATIO_MISSED_PAYMENTS_720D,IP_RATIO_MISSED_PAYMENTS_1080D,IP_RATIO_MISSED_PAYMENTS_2160D,IP_COUNT_DPD_GT0,IP_COUNT_DPD_GT30,IP_COUNT_DPD_GT60,IP_COUNT_DPD_GT90,IP_TOTAL_INSTALLMENTS_COUNT,IP_NUM_PREV_LOANS,IP_NUM_COMPLETED_LOANS,IP_RATIO_AMT_PAID_OWED_360D,IP_RATIO_AMT_PAID_OWED_720D,IP_RATIO_AMT_PAID_OWED_1080D,PCB_FLAG_RISKY_CONTRACT_STATUS_3M,PCB_RATIO_RISKY_STATUS_3M,PCB_FLAG_RISKY_CONTRACT_STATUS_6M,PCB_RATIO_RISKY_STATUS_6M,PCB_FLAG_RISKY_CONTRACT_STATUS_9M,PCB_RATIO_RISKY_STATUS_9M,PCB_FLAG_RISKY_CONTRACT_STATUS_12M,PCB_RATIO_RISKY_STATUS_12M,PCB_FLAG_RISKY_CONTRACT_STATUS_24M,PCB_RATIO_RISKY_STATUS_24M,PCB_LATEST_RISKY_STATUS_FLAG,PCB_NUM_ACTIVE_LOANS_3M,PCB_NUM_ACTIVE_LOANS_6M,PCB_NUM_ACTIVE_LOANS_9M,PCB_NUM_ACTIVE_LOANS_12M,PCB_NUM_ACTIVE_LOANS_24M,PCB_ACTIVE_LOAN_TREND_3M_12M,PCB_MAX_REMAINING_INSTALLMENTS,PCB_SUM_REMAINING_INSTALLMENTS,PCB_MIN_REMAINING_INSTALLMENTS,PCB_INSTALMENT_PROGRESS_MEAN,PCB_INSTALMENT_PROGRESS_MAX,PCB_WORST_DPD_POS_CASH_3M,PCB_WORST_DPD_POS_CASH_6M,PCB_WORST_DPD_POS_CASH_9M,PCB_WORST_DPD_POS_CASH_12M,PCB_WORST_DPD_POS_CASH_24M,PCB_WORST_DPD_POS_CASH_36M,PCB_WORST_DPD_POS_CASH_72M,PCB_WORST_DPD_POS_CASH_96M,WORST_DPD_DEF_POS_CASH_3M,WORST_DPD_DEF_POS_CASH_6M,WORST_DPD_DEF_POS_CASH_9M,WORST_DPD_DEF_POS_CASH_12M,WORST_DPD_DEF_POS_CASH_24M,WORST_DPD_DEF_POS_CASH_36M,WORST_DPD_DEF_POS_CASH_72M,WORST_DPD_DEF_POS_CASH_96M,PCB_LOAN_COMPLETION_RATE,PCB_HISTORY_LENGTH,PA_FLAG_HAS_CREDIT_CARD_HISTORY,PA_RATIO_AMT_CREDIT_TO_ANNUITY_POS,PA_AVG_AMT_ANNUITY_POS,PA_RATIO_AMT_CREDIT_TO_ANNUITY_CASH,PA_AVG_AMT_ANNUITY_CASH,PA_RATIO_AMT_CREDIT_TO_ANNUITY_CARDS,PA_AVG_AMT_ANNUITY_CARDS,PA_NUM_LOANS_POS_360D,PA_NUM_LOANS_POS_720D,PA_NUM_LOANS_POS_1080D,PA_NUM_LOANS_POS_1440D,PA_NUM_LOANS_POS_1800D,PA_NUM_LOANS_Cash_360D,PA_NUM_LOANS_Cash_720D,PA_NUM_LOANS_Cash_1080D,PA_NUM_LOANS_Cash_1440D,PA_NUM_LOANS_Cash_1800D,PA_NUM_LOANS_Cards_360D,PA_NUM_LOANS_Cards_720D,PA_NUM_LOANS_Cards_1080D,PA_NUM_LOANS_Cards_1440D,PA_NUM_LOANS_Cards_1800D,PA_AVG_AMT_CREDIT,PA_MAX_AMT_CREDIT,PA_MIN_AMT_CREDIT,PA_SUM_AMT_CREDIT,PA_RATIO_CREDIT_APPLICATION_POS,PA_RATIO_CREDIT_APPLICATION_Cash,PA_RATIO_CREDIT_APPLICATION_Cards,PA_AVG_DOWN_PAYMENT_RATE,PA_MIN_DOWN_PAYMENT_RATE,PA_MAX_DOWN_PAYMENT_RATE,PA_STD_DOWN_PAYMENT_RATE,PA_AVG_AMT_GOODS_PRICE,PA_MIN_AMT_GOODS_PRICE,PA_MAX_AMT_GOODS_PRICE,PA_STD_AMT_GOODS_PRICE,PA_AVG_PRIVILEGED_RATE_FLAG,FLAG_HAD_RATE_INTEREST_PRIVILEGED,PA_RATIO_REFUSED_LOANS,PA_RATIO_APPROVED_LOANS,PA_LOANS_REFUSED_RECENT_90D,PA_LOANS_REFUSED_RECENT_180D,PA_LOANS_REFUSED_RECENT_360D,PA_LOANS_REFUSED_RECENT_720D,PA_LOANS_REFUSED_RECENT_1080D,PA_LOANS_REFUSED_RECENT_1440D,PA_DAYS_SINCE_LAST_LOAN_APPLY,PA_NUM_HC_REJECT_REASON_90D,PA_NUM_HC_REJECT_REASON_180D,PA_NUM_HC_REJECT_REASON_270D,PA_NUM_HC_REJECT_REASON_360D,PA_NUM_HC_REJECT_REASON_720D,PA_NUM_HC_REJECT_REASON_1080D,FLAG_HC_REJECT_REASON,PA_RATIO_HC_REFUSED_LOANS,PA_NUM_SCO_SCOFR_REJECT_REASON,PA_NUM_LIMIT_REJECT_REASON,PA_UNKNOWN_REJECT_REASON_CNT,PA_RATIO_REPEATER,PA_FLAG_NEW_CLIENT_365D,PA_FLAG_NEW_CLIENT_720D,PA_FLAG_NEW_CLIENT_1080D,PA_RATIO_HIGH_RISK_CHANNEL,PA_RATIO_INSURED_LOANS,PA_FLAG_EVER_INSURED_LOANS,PA_INSURED_LAST_1Y,PA_FLAG_ALWAYS_UNACCOMPANIED,PA_FLAG_NEVER_UNACCOMPANIED,PA_RATIO_UNACCOMPANIED,PA_CNT_UNIQUE_SUITES,PA_RATIO_FAMILY_ACCOMPANIED,PA_RATIO_HIGH_RISK_YIELD_LOANS_360D,PA_RATIO_HIGH_RISK_YIELD_LOANS_720D,PA_RATIO_HIGH_RISK_YIELD_LOANS_1080D,PA_FLAG_HAD_HIGH_RISK_LOAN,PA_AVG_RISK_WEIGHT_180D,PA_MAX_RISK_WEIGHT_180D,PA_AVG_RISK_WEIGHT_360D,PA_MAX_RISK_WEIGHT_360D,PA_AVG_RISK_WEIGHT_720D,PA_MAX_RISK_WEIGHT_720D,PA_AVG_RISK_WEIGHT_1080D,PA_MAX_RISK_WEIGHT_1080D,PA_MEAN_LOAN_REPAYMENT_DIFF_POS,PA_MIN_LOAN_REPAYMENT_DIFF_POS,PA_MAX_LOAN_REPAYMENT_DIFF_POS,PA_MEAN_LOAN_REPAYMENT_DIFF_Cash,PA_MIN_LOAN_REPAYMENT_DIFF_Cash,PA_MAX_LOAN_REPAYMENT_DIFF_Cash,PA_MEAN_LOAN_REPAYMENT_DIFF_Cards,PA_MIN_LOAN_REPAYMENT_DIFF_Cards,PA_MAX_LOAN_REPAYMENT_DIFF_Cards,PA_AVG_LOAN_REPAYMENT_DIFF_CLIENT,PA_MAX_LOAN_REPAYMENT_DIFF_CLIENT,PA_MIN_LOAN_REPAYMENT_DIFF_CLIENT,PA_STD_LOAN_REPAYMENT_DIFF_CLIENT,CB_MAX_MONTHLY_UTIL_1M,CB_UTIL_VOLATILITY_1M,CB_WT_CREDIT_UTIL_1M,CB_MAX_MONTHLY_UTIL_3M,CB_UTIL_VOLATILITY_3M,CB_WT_CREDIT_UTIL_3M,CB_MAX_MONTHLY_UTIL_6M,CB_UTIL_VOLATILITY_6M,CB_WT_CREDIT_UTIL_6M,CB_MAX_MONTHLY_UTIL_9M,CB_UTIL_VOLATILITY_9M,CB_WT_CREDIT_UTIL_9M,CB_MAX_MONTHLY_UTIL_12M,CB_UTIL_VOLATILITY_12M,CB_WT_CREDIT_UTIL_12M,CB_MAX_MONTHLY_UTIL_18M,CB_UTIL_VOLATILITY_18M,CB_WT_CREDIT_UTIL_18M,CB_MAX_MONTHLY_UTIL_24M,CB_UTIL_VOLATILITY_24M,CB_WT_CREDIT_UTIL_24M,CB_WT_CREDIT_UTIL_TREND_3M_12M,AVG_CREDIT_DRAWING_RATIO_3M,AVG_CREDIT_DRAWING_RATIO_12M,CB_TREND_CREDIT_DRAWING_3M_12M,CB_MAX_CREDIT_USAGE_RATIO_1M,CB_WT_CREDIT_USAGE_1M,CB_MAX_CREDIT_USAGE_RATIO_3M,CB_WT_CREDIT_USAGE_3M,CB_MAX_CREDIT_USAGE_RATIO_6M,CB_WT_CREDIT_USAGE_6M,CB_MAX_CREDIT_USAGE_RATIO_9M,CB_WT_CREDIT_USAGE_9M,CB_MAX_CREDIT_USAGE_RATIO_12M,CB_WT_CREDIT_USAGE_12M,CB_MAX_CREDIT_USAGE_RATIO_18M,CB_WT_CREDIT_USAGE_18M,CB_MAX_CREDIT_USAGE_RATIO_24M,CB_WT_CREDIT_USAGE_24M,AVG_ATM_CASH_UTILIZATION_RATIO_3M,AVG_ATM_CASH_UTILIZATION_RATIO_12M,CB_TREND_ATM_CASH_UTILIZATION_3M_12M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_1M,CB_WT_ATM_CASH_UTIL_1M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_3M,CB_WT_ATM_CASH_UTIL_3M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_6M,CB_WT_ATM_CASH_UTIL_6M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_9M,CB_WT_ATM_CASH_UTIL_9M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_12M,CB_WT_ATM_CASH_UTIL_12M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_18M,CB_WT_ATM_CASH_UTIL_18M,CB_MAX_RATIO_ATM_CASH_UTILIZATION_24M,CB_WT_ATM_CASH_UTIL_24M,CB_AVG_ATM_WITHDRAWAL_FREQ_1M,CB_AVG_ATM_WITHDRAWAL_FREQ_3M,CB_AVG_ATM_WITHDRAWAL_FREQ_6M,CB_AVG_ATM_WITHDRAWAL_FREQ_9M,CB_AVG_ATM_WITHDRAWAL_FREQ_12M,CB_AVG_ATM_WITHDRAWAL_FREQ_18M,CB_AVG_ATM_WITHDRAWAL_FREQ_24M,CB_RATIO_MAX_POS_SPEND_1M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_1M,CB_RATIO_MAX_POS_SPEND_3M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_3M,CB_RATIO_MAX_POS_SPEND_6M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_6M,CB_RATIO_MAX_POS_SPEND_9M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_9M,CB_RATIO_MAX_POS_SPEND_12M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_12M,CB_RATIO_MAX_POS_SPEND_18M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_18M,CB_RATIO_MAX_POS_SPEND_24M,CB_MAX_RATIO_POS_TO_TOTAL_DRAW_24M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_1M,CB_RATIO_UNDERPAYMENT_1M,CB_STD_PAYMENT_VOLATILITY_1M,CB_MAX_RATIO_PAYMENT_BALANCE_1M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_3M,CB_RATIO_UNDERPAYMENT_3M,CB_STD_PAYMENT_VOLATILITY_3M,CB_MAX_RATIO_PAYMENT_BALANCE_3M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_6M,CB_RATIO_UNDERPAYMENT_6M,CB_STD_PAYMENT_VOLATILITY_6M,CB_MAX_RATIO_PAYMENT_BALANCE_6M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_9M,CB_RATIO_UNDERPAYMENT_9M,CB_STD_PAYMENT_VOLATILITY_9M,CB_MAX_RATIO_PAYMENT_BALANCE_9M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_12M,CB_RATIO_UNDERPAYMENT_12M,CB_STD_PAYMENT_VOLATILITY_12M,CB_MAX_RATIO_PAYMENT_BALANCE_12M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_18M,CB_RATIO_UNDERPAYMENT_18M,CB_STD_PAYMENT_VOLATILITY_18M,CB_MAX_RATIO_PAYMENT_BALANCE_18M,CB_MAX_RATIO_AMT_PAYMENT_MIN_INST_24M,CB_RATIO_UNDERPAYMENT_24M,CB_STD_PAYMENT_VOLATILITY_24M,CB_MAX_RATIO_PAYMENT_BALANCE_24M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_1M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_3M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_6M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_9M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_12M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_18M,CB_MAX_RATIO_PRINCIPAL_UTILIZATION_24M,CB_WORST_DPD_3M,CB_WORST_DPD_6M,CB_WORST_DPD_9M,CB_WORST_DPD_12M,CB_WORST_DPD_24M,CB_WORST_DPD_36M,CB_WORST_DPD_72M,CB_WORST_DPD_96M,CB_WORST_DPD_DEF_3M,CB_WORST_DPD_DEF_6M,CB_WORST_DPD_DEF_9M,CB_WORST_DPD_DEF_12M,CB_WORST_DPD_DEF_24M,CB_WORST_DPD_DEF_36M,CB_WORST_DPD_DEF_72M,CB_WORST_DPD_DEF_96M
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,NaN,Single,Owned,0.018801,NaN,1,1,0,1,1,0,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,25.920000,1.75,9.990000,5.81,2.007889,0.121978,0.863262,0.060749,ORG_PRIVATE,1,LOW_SKILL,N,Y,Y,N,1,0.167021,33821.746,4.329183,67910.305,0.083037,0.262949,0.179912,0,55597.5,0.0,15686.6320,7812.5000,0.067515,24.170000,0.385417,0.224151,202500.0,1,202500.0,24700.5,406597.50,-43.750000,0,952.951416,1.0,1.275168,0.000000,0.666400,2.129867,0.335360,1.0,1.0,4,157500.0,45000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,-99999.0,-99999.0,-99999.0,-99999.0,-19.0,1.0,0.0,-1.5,-6.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,-99999.0,0.0,-252.600006,-1029.0,0.0,1.0,0.0,0.0,0.0,0.0,245781.0,481988.56,0.509931,49156.2,245781.0,0.0,245781.0,0.284122,0.0,0.009716,1.0,0.284122,-874.00,-103.0,-1437.0,-349.0,-1072.0,780.0,2.0,6.0,0.25,0.75,0.0,0.0,8.0,1822.0,87.0,719.8333,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.00000,1.0,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.000000,0.000000,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,0.0,0.0,0.0,0.0,19.0,1.0,1.0,1.0,1.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-99999.0,1.0,1.0,1.0,1.0,1.0,0.0,-99999.0,-99999.0,-99999.0,0.750000,0.750000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-88888.000000,19.0,0.0,19.353584,9251.775,-99999.000000,-99999.000,-99999.0,-99999.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,179055.00,179055.0,179055.0,179055.0,1.000000,-99999.000000,-99999.0,0.000000,0.000000,0.000000,-99999.000000,179055.00,179055.00,179055.0,-99999.000,0.0,0.0,0.000000,1.000000,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,606.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-99999.0,0.0,0.0,1.0,0.000000,0.0,1.0,1.0,0.000000,0.000000,0.0,-99999.0,0.0,1.0,0.000000,0.0,0.000000,-99999.000000,0.000000,0.000000,0.0,-99999.0,-99999.0,-99999.000000,-99999.0,2.0,2.0,2.000000,2.0,8.0,8.0,8.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,8.0,8.0,8.0,-99999.000000,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

#### bureau balance

In [ ]:
df1 = pd.read_csv(r'D:\home loan credit risk\artifact\data\raw\bureau_balance.csv')
df1.head(15)

#### bureau

In [ ]:
df1 = pd.read_csv(r'D:\home loan credit risk\artifact\data\raw\bureau.csv')
df1.head(15)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
5,215354,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,0.0,Credit card,-31,NaN
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,0.0,Consumer credit,-22,NaN
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,0.0,Consumer credit,-1710,NaN
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,0.0,Consumer credit,-840,NaN
9,162297,5714471,Active,currency 1,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,0.0,Credit card,-690,NaN
10,162297,5714472,Active,currency 1,-1146,0,-180.0,NaN,0.0,0,337500.00,0.00,0.00,0.0,Credit card,-690,NaN
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,675000.00,0.00,0.00,0.0,Consumer credit,-706,NaN
12,162297,5714474,Active,currency 1,-277,0,5261.0,NaN,0.0,0,7033500.00,NaN,NaN,0.0,Mortgage,-31,NaN
13,402440,5714475,Active,currency 1,-96,0,269.0,NaN,0.0,0,89910.00,76905.00,0.00,0.0,Consumer credit,-22,NaN
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.00,0.00,0.00,0.0,Credit card,-185,NaN

#### credit card balance

In [ ]:
df1 = pd.read_csv(r'D:\home loan credit risk\artifact\data\raw\credit_card_balance.csv')
df1.head(15)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.500,0.0,877.500,1700.325,1800.000,1800.000,0.000,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,0.000,2250.000,2250.000,2250.000,60175.080,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.000,0.0,0.000,2250.000,2250.000,2250.000,26926.425,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,0.000,11795.760,11925.000,11925.000,224949.285,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,11547.000,22924.890,27000.000,27000.000,443044.395,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
5,2646502,380010,-7,82903.815,270000,0.0,0.000,0.0,0.000,4449.105,3825.000,3825.000,80519.040,82773.315,82773.315,0.0,0,0.0,0.0,2.0,Active,7,0
6,1079071,171320,-6,353451.645,585000,67500.0,67500.000,0.0,0.000,14684.175,15750.000,15750.000,345433.860,351881.145,351881.145,1.0,1,0.0,0.0,6.0,Active,0,0
7,2095912,118650,-7,47962.125,45000,45000.0,45000.000,0.0,0.000,0.000,264.690,0.000,44735.310,47962.125,47962.125,1.0,1,0.0,0.0,51.0,Active,0,0
8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,199339.425,130.500,4093.515,4093.515,285376.410,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
9,1235299,203885,-5,201261.195,225000,76500.0,111026.700,0.0,34526.700,6338.340,45000.000,45000.000,192793.275,197224.695,197224.695,3.0,9,0.0,6.0,38.0,Active,0,0
10,1108284,209660,-7,102076.560,180000,92250.0,92250.000,0.0,0.000,0.000,4500.000,4500.000,92237.355,94224.060,94224.060,5.0,5,0.0,0.0,0.0,Active,0,0
11,2740914,340339,-1,131669.145,225000,10800.0,10800.000,0.0,0.000,6000.480,6322.500,6322.500,121430.700,127891.935,127891.935,2.0,2,0.0,0.0,6.0,Active,0,0
12,1985699,302517,-4,1427.265,135000,4500.0,101304.720,0.0,96804.720,3023.955,85500.000,85500.000,0.000,0.000,0.000,1.0,30,0.0,29.0,27.0,Active,0,0
13,1441883,171537,-5,0.000,270000,0.0,0.000,0.0,0.000,12218.490,2607.795,1448.640,0.000,0.000,0.000,0.0,0,0.0,0.0,2.0,Active,0,0
14,1864742,303581,-1,0.000,45000,0.0,0.000,0.0,0.000,0.000,2.295,0.000,0.000,0.000,0.000,0.0,0,0.0,0.0,59.0,Active,0,0

#### installment payments

In [ ]:
import pandas as pd
data_path = r'D:\home loan credit risk\artifact\data\raw\installments_payments.csv'
df1 = pd.read_csv(data_path)

In [ ]:
df1['NUM_INSTALMENT_VERSION'].isnull().sum()

np.int64(0)

#### pos cash balance

In [ ]:
data_path = r'D:\home loan credit risk\artifact\data\raw\POS_CASH_balance.csv'
df1 = pd.read_csv(data_path)
df1.head(15)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0
5,2207092,342166,-32,12.0,12.0,Active,0,0
6,1110516,204376,-38,48.0,43.0,Active,0,0
7,1387235,153211,-35,36.0,36.0,Active,0,0
8,1220500,112740,-31,12.0,12.0,Active,0,0
9,2371489,274851,-32,24.0,16.0,Active,0,0
10,2328294,287361,-32,12.0,12.0,Active,0,0
11,2023570,237959,-39,12.0,12.0,Active,0,0
12,1258390,278261,-32,36.0,36.0,Active,0,0
13,1627166,146161,-33,24.0,24.0,Active,0,0
14,1711625,131467,-34,12.0,5.0,Active,0,0

#### previous applications

In [ ]:
data_path = r'D:\home loan credit risk\artifact\data\raw\previous_application.csv'
df1 = pd.read_csv(data_path)
df1.head(15)

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,1,0.0,0.182832,0.867336,XAP,Approved,-73,Cash through the bank,XAP,NaN,Repeater,Mobile,POS,XNA,Country-wide,35,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-164,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Contact center,-1,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Approved,-301,Cash through the bank,XAP,"Spouse, partner",Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-512,Cash through the bank,XAP,NaN,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,Y,1,NaN,NaN,NaN,Repairs,Refused,-781,Cash through the bank,HC,NaN,Repeater,XNA,Cash,walk-in,Credit and cash offices,-1,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN
5,1383531,199383,Cash loans,23703.930,315000.0,340573.5,NaN,315000.0,SATURDAY,8,Y,1,NaN,NaN,NaN,Everyday expenses,Approved,-684,Cash through the bank,XAP,Family,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,18.0,low_normal,Cash X-Sell: low,365243.0,-654.0,-144.0,-144.0,-137.0,1.0
6,2315218,175704,Cash loans,NaN,0.0,0.0,NaN,NaN,TUESDAY,11,Y,1,NaN,NaN,NaN,XNA,Canceled,-14,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
7,1656711,296299,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,7,Y,1,NaN,NaN,NaN,XNA,Canceled,-21,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
8,2367563,342292,Cash loans,NaN,0.0,0.0,NaN,NaN,MONDAY,15,Y,1,NaN,NaN,NaN,XNA,Canceled,-386,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
9,2579447,334349,Cash loans,NaN,0.0,0.0,NaN,NaN,SATURDAY,15,Y,1,NaN,NaN,NaN,XNA,Canceled,-57,XNA,XAP,NaN,Repeater,XNA,XNA,XNA,Credit and cash offices,-1,XNA,NaN,XNA,Cash,NaN,NaN,NaN,NaN,NaN,NaN
10,1715995,447712,Cash loans,11368.620,270000.0,335754.0,NaN,270000.0,FRIDAY,7,Y,1,NaN,NaN,NaN,XNA,Approved,-735,Cash through the bank,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,54.0,low_normal,Cash X-Sell: low,365243.0,-705.0,885.0,-345.0,-334.0,1.0
11,2257824,161140,Cash loans,13832.775,211500.0,246397.5,NaN,211500.0,FRIDAY,10,Y,1,NaN,NaN,NaN,XNA,Approved,-815,Cash through the bank,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,30.0,middle,Cash X-Sell: middle,365243.0,-785.0,85.0,-725.0,-721.0,1.0
12,2330894,258628,Cash loans,12165.210,148500.0,174361.5,NaN,148500.0,TUESDAY,15,Y,1,NaN,NaN,NaN,XNA,Approved,-860,Cash through the bank,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,24.0,high,Cash X-Sell: high,365243.0,-830.0,-140.0,-200.0,-197.0,1.0
13,1397919,321676,Consumer loans,7654.860,53779.5,57564.0,0.0,53779.5,SUNDAY,15,Y,1,0.0,NaN,NaN,XAP,Approved,-408,Cash through the bank,XAP,Unaccompanied,New,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,8.0,low_action,POS household without interest,365243.0,-378.0,-168.0,-168.0,-163.0,1.0
14,2273188,270658,Consumer loans,9644.220,26550.0,27252.0,0.0,26550.0,SATURDAY,10,Y,1,0.0,NaN,NaN,XAP,Approved,-726,Cash through the bank,XAP,NaN,New,Construction Materials,POS,XNA,Stone,83,Consumer electronics,3.0,middle,POS household with interest,365243.0,-693.0,-633.0,-633.0,-627.0,0.0

##  work

In [ ]:
#special_values :
    #both numerator and denominator missing placeholder
DN_MISSING_PLACEHOLDER = - 99999
#numerator missing
N_MISSING_PLACEHOLDER = - 88888
#denominator missing
D_MISSING_PLACEHOLDER = - 77777
# missing value placeholder 
PLACEHOLDER = - 99999
# loan but the data is missing
DPD_LOAN_DATA_MISSING  = -88888

In [ ]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,CB_WORST_DPD_72M,CB_WORST_DPD_96M,CB_WORST_DPD_DEF_3M,CB_WORST_DPD_DEF_6M,CB_WORST_DPD_DEF_9M,CB_WORST_DPD_DEF_12M,CB_WORST_DPD_DEF_24M,CB_WORST_DPD_DEF_36M,CB_WORST_DPD_DEF_72M,CB_WORST_DPD_DEF_96M
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

In [ ]:
SPECIAL_VALUES = [-99999, -88888, -77777]

# special values
special_df = pd.DataFrame({
    'feature': df.columns,
    'special_ratio': df.isin(SPECIAL_VALUES).sum().values / df.shape[0]
})

#zero values
zero_df = (
    (df == 0).sum()
    .div(df.shape[0])
    .reset_index()
    .rename(columns={'index': 'feature', 0: 'zero_ratio'})
)

#Null_values
new_df = (df.isnull().sum() / df.shape[0]).to_frame('null_ratio').reset_index().rename(columns={'index': 'feature'})

In [ ]:
feature_quality_df = special_df.merge(zero_df,on='feature',how='left').merge(new_df,on='feature',how='left')
feature_quality_df

                  feature  special_ratio  zero_ratio  null_ratio
0              SK_ID_CURR       0.000000    0.000000         0.0
1                  TARGET       0.000000    0.919271         0.0
2      NAME_CONTRACT_TYPE       0.000000    0.000000         0.0
3             CODE_GENDER       0.000000    0.000000         0.0
4            FLAG_OWN_CAR       0.000000    0.000000         0.0
..                    ...            ...         ...         ...
311  CB_WORST_DPD_DEF_12M       0.717392    0.277779         0.0
312  CB_WORST_DPD_DEF_24M       0.717392    0.273304         0.0
313  CB_WORST_DPD_DEF_36M       0.717392    0.267275         0.0
314  CB_WORST_DPD_DEF_72M       0.717392    0.246105         0.0
315  CB_WORST_DPD_DEF_96M       0.717392    0.234343         0.0

[316 rows x 4 columns]

In [ ]:
feature_quality_df['max_bad_ratio'] = (
    feature_quality_df[['special_ratio', 'zero_ratio', 'null_ratio']]
    .max(axis=1)
)
feature_quality_df['drop_feature'] = (
    feature_quality_df['max_bad_ratio'] > 0.95
)

In [ ]:
temp = feature_quality_df[feature_quality_df['drop_feature']==True]
drop_features = temp['feature'].values.tolist()

In [ ]:
df.shape

(307511, 316)

In [ ]:
df.drop(columns=drop_features)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,CB_WORST_DPD_72M,CB_WORST_DPD_96M,CB_WORST_DPD_DEF_3M,CB_WORST_DPD_DEF_6M,CB_WORST_DPD_DEF_9M,CB_WORST_DPD_DEF_12M,CB_WORST_DPD_DEF_24M,CB_WORST_DPD_DEF_36M,CB_WORST_DPD_DEF_72M,CB_WORST_DPD_DEF_96M
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0